### PR TITLE
Fixed Login issue

### PR DESCRIPTION
**Pull request by PostsDesert**
-Fixed a login issue where if you tried to open the app again it would crash
-Added Speech Assets for the "Interaction Model" when setting up the skill

### CODE REVIEW

**Comment by Danondso** [comment]
You've been quite busy lol.

**Comment by PostsDesert** [comment]
Half of those commits are me messing up and trying to revert it lol.

**Comment by PostsDesert** [comment]
So __init__.py is not being used. Run the program using GoogleEchoMusicService.py. Im not sure if the __init__ file can be removed but better safe than sorry.  👌

**Comment by Danondso** [comment]
True that, I removed it and it looked like it didn't affect anything when I tested it last night. When I get home today I'll look it over again and double check to make sure everything runs fine. From what it looks like it's going to be fine to remove.

**Comment by PostsDesert** [comment]
Yeah it's all good I took it out and it runs fine.

**Comment by PostsDesert** [comment]
made a new PR for it and some other stuff

**Pull request merged**
